### ISSUE TITLE
Date issues

### ISSUE THREAD

**Issue by BalenD** [BalenD/AO-Api-Prototype-Project#24]
our dates have issues such as its not showing correct date, or even showign a daet, its just counting milisecs since epoch unix time, we gotta fix that.

**Comment by x-mfh** [comment]
changed dates to show correct time, but time is off by a few minutes. Temporary fix with moment.js and adding 2 hours to servertime which is UTC. Look to change server timezone?

**Comment by BalenD** [comment]
all stored dates will be in UTC, let user input and/or see in their own timezone using a frontend script.
