### ISSUE TITLE
User related issues

### ISSUE THREAD

**Issue by Sabeniano** [BalenD/AO-Api-Prototype-Project#32]
- When you create a user and specifies role, it changes the upper case in "Master Administrator", making it an invalid role, aswell as removing an "e" from Employee.

- Also, /users/ URL have the same function as /auth/signin/, except you need Master admin to create a user in /users/, but you still have the option to create one in /auth/signin/.

- Maybe add "role" in /users/, /users/id/ GET request

**Comment by Sabeniano** [comment]
- Also /auth/signin has the same issues as the first issue, except for removing an "e" from Employee.

**Comment by BalenD** [comment]
fixed all in #35
