### ISSUE TITLE
Patching a user

### ISSUE THREAD

**Issue by Sabeniano** [BalenD/AO-Api-Prototype-Project#33]
When you patch a user it loses its ability to get authorization

**Comment by BalenD** [comment]
needs more explanation, what caused it? can you repeat it?

**Comment by Sabeniano** [comment]
![patch](https://user-images.githubusercontent.com/35453938/43629471-a3568f52-96fd-11e8-8090-c282a88216b3.png)

**Comment by BalenD** [comment]
temporary fix in #37, might have to change.
