### ISSUE TITLE
Patching Wallet

### ISSUE THREAD

**Issue by Sabeniano** [BalenD/AO-Api-Prototype-Project#39]
In /employee/ID/wallet, whenever i try to update/patch any information it gets stuck in "Loading". 
![image](https://user-images.githubusercontent.com/35453938/43640501-7f3b66a6-9720-11e8-8c34-d828e82bc36f.png)

**Comment by x-mfh** [comment]
still an issue

**Comment by BalenD** [comment]
fixed in #53
