### ISSUE TITLE
GET /users/ID

### ISSUE THREAD

**Issue by Sabeniano** [BalenD/AO-Api-Prototype-Project#41]
Wont get the individual user (/users/ID/), but can get all of them when using GET /users/

**Comment by Sabeniano** [comment]
- Correction, if the user doesnt have associated employee, you will get an error.
So if you create a user via /auth/signin/ then you wont be able to use the /users/ID/ for that user.

But you will be able to use /users/ID/ for the user, if you create an employee, and it automatically creates the user for you.

**Comment by BalenD** [comment]
fixed in #51
