### ISSUE TITLE
Token related

### ISSUE THREAD

**Issue by Sabeniano** [BalenD/AO-Api-Prototype-Project#42]
After updating/patching a user, you can sign in and get a token, but the is says;  "Not authorized  to perform this action" when trying to GET /users/ after using the new token that is provided.

- This is not a role related issue, i have tried with Employee, Master Administrator and Administrative
- (Note: Can get /employee/)
![image](https://user-images.githubusercontent.com/35453938/43641049-7b6e23e0-9722-11e8-9aea-cbf93ca7106b.png)

**Comment by x-mfh** [comment]
fixed
