### ISSUE TITLE
hateoas links generating

### ISSUE THREAD

**Issue by x-mfh** [BalenD/AO-Api-Prototype-Project#47]
when you find an employee by id, the hateoas links get an additional id
![hateoaslinks1](https://user-images.githubusercontent.com/12151202/43756909-3700466e-9a17-11e8-8274-375fa81f3cff.PNG)

**Comment by BalenD** [comment]
add an boolean option arguement  in the employee models SetUpHyperLinks method, and call the s hlGenerator using it, like this
![issue8](https://user-images.githubusercontent.com/32405839/43758147-81636f20-9a1b-11e8-9b76-0879b03844d8.PNG)
