### ISSUE TITLE
Endpoint decision

### ISSUE THREAD

**Issue by BalenD** [BalenD/AO-Api-Prototype-Project#7]
Instead of having to hit /api/v1/employee/employeeId/***/resourceId to perform read/update operations, we should consider changing it to just /api/v1/employee/employeeId/***/.

why is this possible: because we have a one to one relation there will never be more than one resource belonging to employee, according to our design.

pros: will make it easier for client and potentially require less operation to perform CRUD

cons: might potentially not go by RESTful specification(? not entirely surely)

**Comment by x-mfh** [comment]
we chose to go with /api/v1/employee/employeeId/***/ design. Since we mostly have one to one relations on our employees. Only on schedules will we go with /api/v1/employee/employeeId/***/resourceId.
